@startuml

== Setup ==

mosaik -> SIMONA: world.start("SimonaPowerGrid")
SIMONA -> SIMONA: RunSimonaWithMosaik

== Initialization ==

SIMONA -> MosaikSimulation: initialize()
MosaikSimulation -> MosaikSimulation: SimProcess.startSimulation(...)

mosaik -> SimonaSimulator: init()
SimonaSimulator --> mosaik: meta

mosaik -> SimonaSimulator: SimonaPowerGridEnvironment.create()
SimonaSimulator --> mosaik: entities

mosaik -> SimonaSimulator: PrimaryInputEntities.create()
SimonaSimulator --> mosaik: entities

mosaik -> SimonaSimulator: ResultOutputEntities.create()
SimonaSimulator --> mosaik: entities

mosaik -> SimonaSimulator: setup_done()
SimonaSimulator --> mosaik

== Phase 1 ==
mosaik -> SimonaSimulator: step(...)


@enduml