@startuml
'https://plantuml.com/activity-diagram-beta

start
:Input-Daten (z.B. Wasserstoffbedarf);
:Elektrolyseur;
:Übergabe der Wirk- und Blindleistung;
:Leistungsflussrechnung;
:Übergabe der Knotenspannungen und Leitungsströme;
:Monitoring in der Leitwarte;
stop

@enduml
